#Main
/:
  controller: Main 
  action: index
  security: 0
  isAdmin: 0

/installation:
  controller: Main 
  action: install
  security: 0
  isAdmin: 0

/se-connecter:
  controller: User
  action: login
  security: 0
  isAdmin: 0


/se-deconnecter:
  controller: User
  action: logout
  security: 0
  isAdmin: 0


/s-inscrire:
  controller: User
  action: register
  security: 0
  isAdmin: 0


/home:
  controller: Main
  action: admin
  security: 0
  isAdmin: 0



/confirmation-mail:
  controller: User
  action: confirmMail
  security: 0
  isAdmin: 0


/mot-de-passe-oublie:
  controller: User
  action: forgotPasswd
  security: 0
  isAdmin: 0


/reinitialisation-mot-de-passe:
  controller: User
  action: resetPasswd
  security: 0
  isAdmin: 0


/modifier-utilisateur:
  controller: User
  action: edit
  security: 0
  isAdmin: 0


/utilisateurs:
  controller: User
  action: list
  security: 0
  isAdmin: 0


/tableau-de-bord:
  controller: Admin
  action: dashboard
  security: 0
  isAdmin: 0

/stats:
  controller: Statistiques
  action: stats
  security: 0
  isAdmin: 0



### PROFIL ###

/profil:
  controller: Profil
  action: index
  security: 0
  isAdmin: 0

/profil-notification:
  controller: Profil
  action: manageNotification
  security: 0
  isAdmin: 0

/profil-gestion-des-comptes:
 controller: Profil
 action: manageAccount
 security: 0
 isAdmin: 0

/profil-securite:
  controller: Profil
  action: manageSecurity
  security: 0
  isAdmin: 0
  
/profil-contact:
 controller: Profil
 action: manageContact
 security: 0
 isAdmin: 0

/profil-aide-et-support:
 controller: Profil
 action: help
 security: 0
 isAdmin: 0
 
/profil-conditions-generale-d-utilisation:
 controller: Profil
 action: condition
 security: 0
 isAdmin: 0

### Parameters ####
/parametres:
  controller: Parameters
  action: index
  security: 0
  isAdmin: 0

/parametres-gestion-compte: 
  controller: Parameters
  action: parametersAccountManagement
  security: 0
  isAdmin: 0

/parametres-gestion-utilisateurs:
  controller: UsersManagement
  action: index
  security: 0
  isAdmin: 0

/parametres-support:
  controller: Parameters
  action: parametersSupport
  security: 0
  isAdmin: 0

/parametres-users:
  controller: Parameters
  action: parametersUsers
  isAdmin: 0

/parametres-add-user:
  controller: Parameters
  action: parametersAddUser
  security: 0
  isAdmin: 0

/parametres-edit-user:
  controller: Parameters
  action: parametersEditUser
  security: 0
  isAdmin: 0

/parametres-compte:
  controller: Parameters
  action: parametersAccount
  security: 0
  isAdmin: 0

/parametres-site:
  controller: Parameters
  action: parametersUpdateSite
  security: 0
  isAdmin: 0

/parametres-support:
  controller: Parameters
  action: parametersSupport
  security: 0
  isAdmin: 0

/parametres-affichage:
  controller: Parameters
  action: parametersAppearance
  security: 0
  isAdmin: 0

/set-appearance:
  controller: Parameters
  action: setAppearance
  security: 0
  isAdmin: 0

/parametres-users:
  controller: Parameters
  action: parametersUsers
  security: 0
  isAdmin: 0

/parametres-compte:
  controller: Parameters
  action: parametersAccount
  security: 0
  isAdmin: 0

/parametres-url:
  controller: Parameters
  action : manageUrl
  security : 0
  isAdmin: 0

 ### ARTICLE ###

/article:
  controller: Article
  action: index
  security: 0
  isAdmin: 0

/article-add:
  controller: Article
  action: saveArticle
  security: 0
  isAdmin: 0

/article-read:
  controller: Article
  action: readArticle
  security: 0
  isAdmin: 0

# /article-edition/{id}:
# controller: Article
# action: editArticle


### CATEGORY ###

/category:
  controller: Category
  action: index
  security: 0
  isAdmin: 0

/category-add:
  controller: Category
  action: saveCategory
  security: 0
  isAdmin: 0
 
### COMMENTAIRE ###

/commentaire:
  controller: Commentaire
  action: index
  security: 0
  isAdmin: 0

/commentaire-add:
  controller: Commentaire
  action: saveComment
  security: 0
  isAdmin: 0
  
/commentaire-edition:
 controller: Commentaire
 action: saveComment
 security: 0
 isAdmin: 0

/commentaire-mots-bannis:
 controller: Commentaire
 action: motsbannis
 security: 0
 isAdmin: 0

/supprimer-mot-banni:
  controller: Commentaire
  action: removeBanWord
  security: 0
  isAdmin: 0

/signaler:
  controller: Commentaire
  action: signaler
  security: 0
  isAdmin: 0
 
  ### PAGE ###

/page:
  controller: Page
  action: index
  security: 0
  isAdmin: 0

/page-add:
  controller: Page
  action: savePage
  security: 0
  isAdmin: 0

/page-edit/{id}:
 controller: Page
 action: editPage
 security: 0
 isAdmin: 0
 
/page/{id}:
 controller: Page
 action: showPage
 security: 0
 isAdmin: 0

  ### NAVIGATION ###

/navigation:
  controller: Navigation
  action: index
  security: 0
  isAdmin: 0

/navigation-menu-add:
  controller: Navigation
  action: saveMenu
  security: 0
  isAdmin: 0
  

  ### THEME ###

/theme:
  controller: Commentaire
  action: index
  security: 0
  isAdmin: 0
  
  ### MEDIAS ###

/media:
  controller: Media
  action: index
  security: 0
  isAdmin: 1

/ajout-medias:
  controller: Media
  action: addComment
  security: 0
  isAdmin: 0
  
/medias/{id}:
 controller: Media
 action: showMedia
 security: 0
 isAdmin: 0

  ### APPARENCES ###

/apparence:
  controller: Apparence
  action: index
  security: 0
  isAdmin: 0
  
  ### GRID & COMPONENTS ###

/grid:
  controller: WebCreator
  action: grid
  security: 0
  isAdmin: 0

/components:
  controller: WebCreator
  action: components
  security: 0
  isAdmin: 0

### DATA TABLE
/datatable:
  controller: DataTable
  action: index
  security: 0
  isAdmin: 0

/site:
  controller: Site
  action: getMainPage
  security: 0
  isAdmin: 0

/site/page?id:
  controller: Site
  action: getPage
  security: 0
  isAdmin: 0

/site/page?name:
  controller: Site
  action: getPage
  security: 0
  isAdmin: 0
