#Main

/:
  controller: Main 
  action: index

/se-connecter:
  controller: User
  action: login

/se-deconnecter:
  controller: User
  action: logout
/s-inscrire:
  controller: User
  action: register

/home:
  controller: Main
  action: admin
/confirmation-mail:
  controller: User
  action: confirmMail

/mot-de-passe-oublie:
  controller: User
  action: forgotPasswd

/reinitialisation-mot-de-passe:
  controller: User
  action: resetPasswd

/modifier-utilisateur:
  controller: User
  action: edit

/utilisateurs:
  controller: User
  action: list

/tableau-de-bord:
  controller: Admin
  action: dashboard


### PROFIL ###

/profil:
  controller: Profil
  action: index

/profil-notification:
  controller: Profil
  action: manageNotification

  
/profil-langue:
 controller: Profil
 action: manageLanguage

/profil-gestion-des-comptes:
 controller: Profil
 action: manageAccount

/profil-securite:
  controller: Profil
  action: manageSecurity
  
/profil-contact:
 controller: Profil
 action: manageContact

/profil-aide-et-support:
 controller: Profil
 action: help
  
/profil-conditions-generale-d-utilisation:
 controller: Profil
 action: condition

### Parameters ####
/parametres:
  controller: Parameters
  action: index

/parametres-gestion-compte: 
  controller: Parameters
  action: AccountManagement

/parametres-gestion-utilisateurs:
  controller: UsersManagement
  action: index

/parametres-support:
  controller: Parameters
  action: parametersSupport
/parametres-langue:
  controller: Parameters
  action: parametersLangue
 ### ARTICLE ###

/article:
  controller: Article
  action: index

/article-add:
  controller: Article
  action: addArticle

# /article-edition/{id}:
# controller: Article
# action: editArticle
#
#/article/{id}:
# controller: Article
# action: showArticle

### COMMENTAIRE ###

/commentaire:
  controller: Commentaire
  action: index

/commentaire-add:
  controller: Commentaire
  action: addComment

/commentaire-mots-bannis:
 controller: Commentaire
 action: motsbannis
 
/commentaire/{id}:
 controller: Commentaire
 action: showCommentaire 


  ### EXTENSION ###

/extension:
  controller: Extension
  action: index
  
  ### PAGE ###

/page:
  controller: Page
  action: index

/page-add:
  controller: Page
  action: addPage
  
/page-edit/{id}:
 controller: Page
 action: editPage
 
/page/{id}:
 controller: Page
 action: showPage

  ### NAVIGATION ###

/navigation:
  controller: Navigation
  action: index
  
# /ajout-menu-navigation:
#   controller: Navigation
#   action: notification
  
# /edition-menu-navigation/{id}:
#  controller: Navigation
#  action: editNavigation

  ### THEME ###

/theme:
  controller: Commentaire
  action: index
  
/commentaire-edition/{id}:
 controller: Commentaire
 action: editComment

  ### MEDIAS ###

/media:
  controller: Media
  action: index

/ajout-medias:
  controller: Media
  action: addComment
  
/medias/{id}:
 controller: Media
 action: showMedia

  ### APPARENCES ###

/apparence-theme:
  controller: Apparence
  action: editTheme

/apparence-page:
  controller: Apparence
  action: editPage

/apparence-menu:
  controller: Apparence
  action: editMenu

  ### GRID & COMPONENTS ###

/grid:
  controller: WebCreator
  action: grid

/components:
  controller: WebCreator
  action: components
