#Main
/site:
  controller: Main 
  action: index
  security: 0
  isAdmin: 0

/installation:
  controller: Main 
  action: install
  security: 0
  isAdmin: 0

/se-connecter:
  controller: User
  action: login
  security: 0
  isAdmin: 0


/se-deconnecter:
  controller: User
  action: logout
  security: 0
  isAdmin: 0


/s-inscrire:
  controller: User
  action: register
  security: 0
  isAdmin: 0

/confirmation-mail:
  controller: User
  action: confirmMail
  security: 0
  isAdmin: 0


/mot-de-passe-oublie:
  controller: User
  action: forgotPasswd
  security: 0
  isAdmin: 0


/reinitialisation-mot-de-passe:
  controller: User
  action: resetPasswd
  security: 0
  isAdmin: 0

/tableau-de-bord:
  controller: Admin
  action: dashboard
  security: 1
  isAdmin: 0

/stats:
  controller: Statistiques
  action: stats
  security: 1
  isAdmin: 0

### Parameters ####
/parametres:
  controller: Parameters
  action: index
  security: 1
  isAdmin: 0

/parametres-gestion-compte: 
  controller: Parameters
  action: parametersAccountManagement
  security: 1
  isAdmin: 0

/parametres-users:
  controller: Parameters
  action: parametersUsers
  security: 1
  isAdmin: 1

/parametres-add-user:
  controller: Parameters
  action: parametersAddUser
  security: 1
  isAdmin: 1

/parametres-edit-user:
  controller: Parameters
  action: parametersEditUser
  security: 1
  isAdmin: 0

/parametres-compte:
  controller: Parameters
  action: parametersAccount
  security: 1
  isAdmin: 1

/parametres-site:
  controller: Parameters
  action: parametersUpdateSite
  security: 1
  isAdmin: 1

/parametres-affichage:
  controller: Parameters
  action: parametersAppearance
  security: 1
  isAdmin: 1

/set-appearance:
  controller: Parameters
  action: setAppearance
  security: 1
  isAdmin: 1

/parametres-url:
  controller: Parameters
  action : manageUrl
  security : 0
  isAdmin: 1

 ### ARTICLE ###

/article:
  controller: Article
  action: index
  security: 1
  isAdmin: 0

/article-add:
  controller: Article
  action: saveArticle
  security: 1
  isAdmin: 0

### CATEGORY ###

/category:
  controller: Category
  action: index
  security: 1
  isAdmin: 0

/category-add:
  controller: Category
  action: saveCategory
  security: 1
  isAdmin: 0
 
### COMMENTAIRE ###

/commentaire:
  controller: Commentaire
  action: showComments
  security: 1
  isAdmin: 0

/commentaire-add:
  controller: Commentaire
  action: saveComment
  security: 1
  isAdmin: 0

/comment-delete:
  controller: Commentaire
  action: deleteComment
  security: 1
  isAdmin: 0

/comment-approve:
  controller: Commentaire
  action: approveComment
  security: 1
  isAdmin: 0

/comment-unapprove:
  controller: Commentaire
  action: unapproveComment
  security: 1
  isAdmin: 0

/commentaire-mots-bannis:
 controller: Commentaire
 action: motsbannis
 security: 1
 isAdmin: 0

/supprimer-mot-banni:
  controller: Commentaire
  action: removeBanWord
  security: 1
  isAdmin: 0

/signaler:
  controller: Commentaire
  action: signaler
  security: 1
  isAdmin: 0
 
  ### PAGE ###

/pages:
  controller: Page
  action: index
  security: 1
  isAdmin: 0

/page-add:
  controller: Page
  action: savePage
  security: 1
  isAdmin: 0


  ### NAVIGATION ###

/navigation:
  controller: Navigation
  action: index
  security: 1
  isAdmin: 0

/navigation-menu-add:
  controller: Navigation
  action: saveMenu
  security: 1
  isAdmin: 0
  

  ### THEME ###

/theme:
  controller: Commentaire
  action: index
  security: 1
  isAdmin: 0
  
  ### MEDIAS ###

/media:
  controller: Media
  action: index
  security: 1
  isAdmin: 1

/ajout-medias:
  controller: Media
  action: addComment
  security: 1
  isAdmin: 0

  ### APPARENCES ###

/apparence:
  controller: Apparence
  action: index
  security: 1
  isAdmin: 0

### DATA TABLE ###
/datatable:
  controller: DataTable
  action: index
  security: 1
  isAdmin: 0

/:
  controller: Site
  action: showPosts
  security: 1
  isAdmin: 0

/post:
  controller: Site
  action: showSinglePost
  security: 0
  isAdmin: 0

/page:
  controller: Site
  action: showSinglePage
  security: 0
  isAdmin: 0

/sakura:
  controller: Main
  action: download
  security: 0
  isAdmin: 0

### 404 ###

/page-not-found:
  controller: Main
  action: pageNotFound
  security: 0
  isAdmin: 0